# Get all users
GET /api/users
Host: localhost:5277
Content-Type: application/json
###

# Get a user by ID
GET /api/users/1
Host: localhost:5277
Content-Type: application/json
###

# Create a new user
POST /api/users
Host: localhost:5277
Content-Type: application/json

{
    "Id": 7,
    "Name": "",
    "Email": "john.doe@aaa.com"
}
###

# Update an existing user by ID
PUT /api/users/5
Host: localhost:5277
Content-Type: application/json

{
    "Id": 5,
    "Name": "Jane Doe",
    "Email": "jane.doe@example.com"
}
###

# Delete a user by ID
DELETE /api/users/5
Host: localhost:5277
Content-Type: application/json

###
# Test error handling middleware
GET /api/users/error
Host: localhost:5277
Content-Type: application/json
###
# Test token validation middleware
POST /api/users
Host: localhost:5277
Content-Type: application/json
Authorization: valid-token

{
    "Id": 7,
    "Name": "Abu",
    "Email": "john.doe@aaa.com"
}
###
POST /api/users
Host: localhost:5277
Content-Type: application/json
Authorization: invalid-token

{
    "Id": 7,
    "Name": "Abu",
    "Email": "john.doe@aaa.com"
}